title: "UIL Documentation"
description: UIL Website Documentation
remote_theme: pmarsceill/just-the-docs
color_scheme: "light"
search_enabled: true
exclude: []
mybase: "/myDocsTest/docs"

# Aux links for the upper right navigation
aux_links:
  "UIL Docs on GitHub":
    - "//github.com/AAHOM/UILDOC"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: false

# Sort order for navigation links
# nav_sort: case_insensitive # default, equivalent to nil
nav_sort: case_sensitive # Capital letters sorted before lowercase

# Footer content
# appears at the bottom of every page's main content

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"


footer_content: "Copyright &copy; 2022 George Crane. Distributed by an <a href=\"https://github.com/pmarsceill/just-the-docs/tree/master/LICENSE.txt\">MIT license.</a>"
